# Generated by Django 4.2.6 on 2023-10-16 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveIntegerField(choices=[(1, 'completed'), (2, 'rejected')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(null=True)),
                ('customer_external_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_customers.customer', to_field='external_id')),
                ('loan_external_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_loans.loan', to_field='external_id')),
            ],
        ),
    ]
