# Generated by Django 4.2.6 on 2023-10-16 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveIntegerField(choices=[(1, 'pending'), (2, 'active'), (3, 'rejected'), (4, 'paid')], default=1)),
                ('contract_version', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maximun_payment_date', models.DateTimeField(null=True)),
                ('taken_at', models.DateTimeField(null=True)),
                ('customer_external_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_customers.customer', to_field='external_id')),
            ],
        ),
    ]
